chore: wip

diff --git a/release2 b/release2
--- a/release2
+++ b/release2
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-
 # MIT License
 #
 # Copyright (c) 2021 Northscaler, Inc.
@@ -22,29 +21,181 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-# This script implements the minor-release-per-branch workflow projects using git for source control.
-
-if [ -n "$RELEASE_DEBUG" ]; then
-  set -x
-fi
+# This script implements a minor-release-per-branch workflow projects using git for source control.
 
 set -e
 
-THIS_ABSPATH="$(cd "$(dirname "$0")"; pwd)"
+THIS_ABSPATH="$(
+  cd "$(dirname "$0")"
+  pwd
+)"
 
 ORIGIN=${ORIGIN:-origin}
 MAIN=${MAIN:-main}
 TAG_PREFIX=${TAG_PREFIX:-''}
 TAG_SUFFIX=${TAG_SUFFIX:-''}
 BRANCH_PREFIX=${BRANCH_PREFIX:-'v'}
-BRANCH_SUFFIX=${BRANCH_SUFFIX:-''} # '.x' is a common one
+BRANCH_SUFFIX=${BRANCH_SUFFIX:-''}     # '.x' is a common one
 GIT_COMMIT_OPTS=${GIT_COMMIT_OPTS:-''} # --no-verify is a common one
-GIT_PUSH_OPTS=${GIT_PUSH_OPTS:-''} # --no-verify is a common one
-PRE=${PRE:-pre}
-RC=${RC:-rc}
+GIT_PUSH_OPTS=${GIT_PUSH_OPTS:-''}     # --no-verify is a common one
+DEFAULT_PRE=${DEFAULT_PRE:-pre}
+DEFAULT_RC=${DEFAULT_RC:-rc}
+PRE=${PRE:-$DEFAULT_PRE}
+RC=${RC:-$DEFAULT_RC}
+VERBOSE=${VERBOSE:-''}
 
-if [ -z "$NO_GIT_DISCOVERY_ACROSS_FILESYSTEM" ]; then
-  GIT_DISCOVERY_ACROSS_FILESYSTEM=1 # needed when running in a docker container
+usage() {
+  echo "Performs release commits, tags & branching"
+
+  PRE_USAGE=$DEFAULT_PRE
+  if [ "$PRE" != "$DEFAULT_PRE" ]; then
+    PRE_USAGE="$PRE_USAGE|$PRE"
+  fi
+
+  RC_USAGE=$DEFAULT_RC
+  if [ "$RC" != "$DEFAULT_RC" ]; then
+    RC_USAGE="$RC_USAGE|$RC"
+  fi
+
+  echo Usage:
+  printf "%s --tech tech1,tech2,... [options] $PRE_USAGE|$RC_USAGE|minor|patch\n \
+  where options are:\n \
+  --tech|-t                           # required at least once, the technology type to release, comma-delimited supported; choose from:\n \
+                                      #  'chart' for Helm Chart (Chart.yaml),\n \
+                                      #  'image' for Docker Image (Dockerfile),\n \
+                                      #  'nodejs' for Node.js (package.json),\n \
+                                      #  'sbt' for Scala (build.sbt),\n \
+                                      #  'gradle' for Gradle (build.gradle),\n \
+                                      #  'gradlekts' for Kotlin Gradle (build.gradle.kts),\n \
+                                      #  'mavenxml' for Maven XML (pom.xml),\n \
+                                      #  'version' for plain text version file (VERSION),\n \
+  [--origin|-o origin]                # optional, git origin, default '%s'\n \
+  [--main|-m main]                    # optional, git main branch, default '%s'\n \
+  [--release-tag-prefix|-p prefix]    # optional, git release tag prefix, default '%s'\n \
+  [--release-tag-suffix|-s suffix]    # optional, git release tag suffix, default  '%s'\n \
+  [--release-branch-prefix|-P prefix] # optional, git release branch prefix, default '%s'\n \
+  [--release-branch-suffix|-S suffix] # optional, git release branch suffix, default '%s' ('.x' is common)\n \
+  [--git-commit-opts|-o opts]         # optional, git commit options, default '%s' ('--no-verify' is common)\n \
+  [--git-push-opts|-O opts]           # optional, git commit options, default '%s' ('--no-verify' is common)\n \
+  [--pre-release-token|-k token]      # optional, pre release token, default '%s'\n \
+  [--rc-release-token|-K token]       # optional, release candidate release token, default '%s'\n \
+  [--devqa|-d]                        # optional, shortcut for '--pre-release-token dev --rc-release-token qa'\n \
+  [--alphabeta|-a]                    # optional, shortcut for '--pre-release-token alpha --rc-release-token beta'\n \
+  [--verbose|-v]                      # optional, displays detailed progress\n \
+  [--help|-h]                         # optional, displays usage\n" \
+    "$0" \
+    "$ORIGIN" \
+    "$MAIN" \
+    "$TAG_PREFIX" \
+    "$TAG_SUFFIX" \
+    "$BRANCH_PREFIX" \
+    "$BRANCH_SUFFIX" \
+    "$GIT_COMMIT_OPTS" \
+    "$GIT_PUSH_OPTS" \
+    "$PRE" \
+    "$RC"
+
+  echo To release a pre release from the "'$MAIN'" branch only, use "'$DEFAULT_PRE'" or "'$PRE'"
+  echo To release a release candidate release from the "'$RC'" branch only, use "'$DEFAULT_RC'" or "'$RC'"
+  echo To release the first minor release from the "'$RC'" branch only, use "'minor'"
+  echo To release a patch from the "'$RC'" branch only, use "'patch'"
+}
+
+# process args
+while [ $# -gt 0 ]; do
+  case "$1" in
+  --tech | -t)
+    shift
+    TECH="$TECH,$1"
+    shift
+    ;;
+  --origin | -o)
+    shift
+    ORIGIN="$1"
+    shift
+    ;;
+  --main | -m)
+    shift
+    MAIN="$1"
+    shift
+    ;;
+  --release-tag-prefix | -p)
+    shift
+    TAG_PREFIX="$1"
+    shift
+    ;;
+  --release-tag-suffix | -s)
+    shift
+    TAG_SUFFIX="$1"
+    shift
+    ;;
+  --release-branch-prefix | -P)
+    shift
+    BRANCH_PREFIX="$1"
+    shift
+    ;;
+  --release-branch-suffix | -S)
+    shift
+    BRANCH_SUFFIX="$1"
+    shift
+    ;;
+  --pre-release-token | -k)
+    shift
+    PRE="$1"
+    shift
+    ;;
+  --rc-release-token | -K)
+    shift
+    RC="$1"
+    shift
+    ;;
+  --devqa | -d)
+    PRE=dev
+    RC=qa
+    shift
+    ;;
+  --alphabeta | -a)
+    PRE=alpha
+    RC=beta
+    shift
+    ;;
+  --verbose | -v)
+    VERBOSE=1
+    shift
+    ;;
+  --help | -h)
+    usage >&2
+    exit 0
+    ;;
+  *)
+    usage >&2
+    exit 1
+    ;;
+  esac
+done
+
+# validations
+
+# ensure at least one tech given
+TECHNOLOGIES="$(echo -n "$TECH" | tr ',' ' ' | xargs)"
+if [ -z "$TECHNOLOGIES" ]; then
+  echo "ERROR: no technologies given" >&2
+  usage >&2
+  exit 1
+fi
+
+# ensure pre & rc tokens are not the same
+if [ "$PRE" == "$RC" ]; then
+  echo "ERROR: pre release token ($PRE) cannot be the same as release candidate release token ($RC)" >&2
+  usage >&2
+  exit 1
+fi
+
+# ensure pre token sorts alphabetically before rc token
+if [ "$PRE" \> "$RC" ]; then
+  echo "ERROR: pre release token ($PRE) cannot sort after release candidate release token ($RC)" >&2
+  usage >&2
+  exit 1
 fi
 
 MATCH=match
@@ -62,38 +213,6 @@ if ! which $XMLSTARLET; then
   export XMLSTARLET="docker run --rm -i jakubsacha/docker-$XMLSTARLET"
 fi
 
-PRE_USAGE=pre
-if [ "$PRE" != "pre" ]; then
-  PRE_USAGE="$PRE_USAGE|$PRE"
-fi
-
-RC_USAGE=rc
-if [ "$RC" != "rc" ]; then
-  RC_USAGE="$RC_USAGE|$RC"
-fi
-
-# ensure pre & rc tokens are not the same
-if [ "$PRE" == "$RC" ]; then
-  echo "ERROR: PRE ($PRE) cannot be the same as RC ($RC)" >&2
-  exit 1
-fi
-
-# ensure pre token sorts alphabetically before rc token
-if [ "$PRE" \> "$RC" ]; then
-  echo "ERROR: PRE ($PRE) cannot sort alphabetically after RC ($RC)" >&2
-  exit 1
-fi
-
-if [ $# -lt 2 ]; then
-  echo "Insufficient arguments" >&2
-  echo "Usage: $0 <technology-type>[+<technology-type2>+[<technology-type3>+...]] <release-level>" >&2
-  echo "Example 1: $0 nodejs pre # releases via npm using package.json" >&2
-  echo "Example 2: $0 nodejs+image pre # releases via npm using package.json and versions Dockerfile with it" >&2
-  exit 1
-fi
-
-TECHNOLOGIES="$(echo "$1" | tr '+' ' ')"
-
 # Source technology-specific file(s) for usage_xxx, getVersion_xxx & setVersion_xxx functions
 for T in $TECHNOLOGIES; do
   FUNCTIONS_FILE="$THIS_ABSPATH/release-$T"
@@ -101,7 +220,7 @@ for T in $TECHNOLOGIES; do
     source "$FUNCTIONS_FILE"
   else
     echo "Unknown technology type: $T" >&2
-    echo "Usage: $0 <technology-type> <release-level>" >&2
+    usage >&2
     exit 1
   fi
 done
@@ -113,41 +232,35 @@ setVersions() {
   done
 }
 
-usages() {
-  for T in $TECHNOLOGIES; do
-    usage_$T
-  done
-}
-
 RELEASE_LEVEL="${@: -1}"
 
 case "$RELEASE_LEVEL" in
-  major|minor|patch|pre|rc|$PRE|$RC)
-    # ok
-    ;;
-  h|he|hel|help)
-    usages
-    exit 0
-    ;;
-  *)
-    if [ -n "$2" ]; then
-      echo "ERROR: specify release level of 'pre' or '$PRE' for prerelease, 'rc' or '$RC' for release candidate, 'patch', 'minor', or 'major'" >&2
-    fi
-    usages
-    exit 1
-    ;;
+minor | patch | $DEFAULT_PRE | $DEFAULT_RC | $PRE | $RC)
+  # ok
+  ;;
+*)
+  echo "ERROR: specify release level of minor|patch|$DEFAULT_PRE|$DEFAULT_RC|$PRE|$RC" >&2
+  usage >&2
+  exit 1
+  ;;
 esac
 
-echo "INFO: checking required preconditions"
+verbose() {
+  if [ -n "$VERBOSE" ]; then
+    echo "$1"
+  fi
+}
 
-git pull
+verbose "INFO: checking required preconditions"
+
+git pull $ORIGIN
 
 # check that all versions are exactly the same
 for T in $TECHNOLOGIES; do
   V="$(getVersion_$T)"
   if [ -n "$V_LAST" ] && [ "$V_LAST" != "$V" ]; then
     echo "ERROR: versions among different technology files differ: $T is at $V, but $T_LAST is at $V_LAST" >&2
-    exit 33
+    exit 3
   fi
   V_LAST="$V"
   T_LAST="$T"
@@ -157,21 +270,21 @@ if ! git diff --exit-code --no-patch; then
   echo 'ERROR: you have modified tracked files; only release from clean directories!' >&2
   exit 3
 else
-  echo 'INFO: no modified tracked files'
+  verbose 'INFO: no modified tracked files'
 fi
 
 if ! git diff --cached --exit-code --no-patch; then
   echo 'ERROR: you have cached modified tracked files; only release from clean directories!' >&2
   exit 3
 else
-  echo 'INFO: no cached modified tracked files'
+  verbose 'INFO: no cached modified tracked files'
 fi
 
 if [ -n "$(git status -s)" ]; then
   echo 'ERROR: You have unignored untracked files; only release from clean directories!' >&2
   exit 3
 else
-  echo 'INFO: no unignored untracked files'
+  verbose 'INFO: no unignored untracked files'
 fi
 
 BRANCH="$(git status | head -n 1 | awk '{ print $3 }')"
@@ -179,39 +292,39 @@ if ! $MATCH "^($MAIN|$BRANCH_PREFIX[0-9]{1,}\.[0-9]{1,}$BRANCH_SUFFIX)$" "$BRANC
   echo "ERROR: you can only release from the $MAIN branch or release branches! You are currently on $BRANCH" >&2
   exit 3
 else
-  echo "INFO: on branch $BRANCH, from which releases are allowed"
+  verbose "INFO: on branch $BRANCH, from which releases are allowed"
 fi
 
 if ! git diff --exit-code -no-patch $BRANCH $ORIGIN/$BRANCH; then
   echo "ERROR: Local branch $BRANCH differs from remote branch $ORIGIN/$BRANCH" >&2
   exit 3
 else
-  echo "INFO: no differences between local & remote branch $BRANCH"
+  verbose "INFO: no differences between local & remote branch $BRANCH"
 fi
 
-if [ "$BRANCH" = "$MAIN" ]; then
+if [ "$BRANCH" == "$MAIN" ]; then
   case "$RELEASE_LEVEL" in
-    pre|rc|$PRE|$RC)
+    $DEFAULT_PRE|$DEFAULT_RC|$PRE|$RC)
       # ok
       ;;
     *)
-      echo "ERROR: only 'pre'/'$PRE' or 'rc'/'$RC' releases are permitted from the $MAIN branch." >&2
-      exit 6
+      echo "ERROR: only '$DEFAULT_PRE'/'$PRE' or '$DEFAULT_RC'/'$RC' releases are permitted from the $MAIN branch." >&2
+      exit 3
       ;;
   esac
 else # this is a release branch
   case "$RELEASE_LEVEL" in
-      rc|$RC|patch|minor|major)
+      $DEFAULT_RC|$RC|patch|minor)
         # ok
         ;;
       *)
-        echo "ERROR: only 'rc'/'$RC', 'patch', 'minor', or 'major' releases are permitted from a release branch." >&2
-        exit 7
+        echo "ERROR: only '$DEFAULT_RC'/'$RC', 'patch', or 'minor' releases are permitted from a release branch." >&2
+        exit 3
         ;;
   esac
 fi
 
-echo "INFO: ok to proceed with $RELEASE_LEVEL from branch $BRANCH"
+verbose "INFO: ok to proceed with $RELEASE_LEVEL from branch $BRANCH"
 
 VERSION="$V_LAST"
 
@@ -220,18 +333,18 @@ if ! $MATCH "\-($PRE|$RC)\.[0-9]{1,}$" "$VERSION"; then
   exit 3
 fi
 
-# usage: apply message [tag [remote branch]]
+# usage: apply message [tag [remote [branch]]]
 applyChanges() {
   git add .
   git commit --allow-empty -m "$1" $GIT_COMMIT_OPTS
-  echo "INFO: committed changes with message: $1"
+  verbose "INFO: committed changes with message: $1"
 
   MSG="INFO: pushed commits"
 
   if [ -n "$2" ]; then
     tag="$TAG_PREFIX$2$TAG_SUFFIX"
     git tag "$tag"
-    echo "INFO: tagged $tag"
+    verbose "INFO: tagged $tag"
     MSG="$MSG & tags"
   fi
 
@@ -244,16 +357,16 @@ applyChanges() {
   git push $GIT_PUSH_OPTS $SET_UPSTREAM_ARGS
   git push --tags
 
-  echo "$MSG"
+  verbose "$MSG"
 }
 
-if [ "$BRANCH" = "$MAIN" ]; then # this will be either an rc, resulting in a new release branch, or a pre
+if [ "$BRANCH" == "$MAIN" ]; then # this will be either an rc, resulting in a new release branch, or a pre
   set +e
   MATCHES="$($MATCH "^([0-9]{1,})\.([0-9]{1,})\.0\-$PRE\.([0-9]{1,})$" "$VERSION")"
   set -e
   if [ -z "$MATCHES" ]; then
     echo "ERROR: the version does not match the format of major.minor.0-$PRE.n required in the $MAIN branch." >&2
-    exit 8
+    exit 3
   else
     echo "INFO: version $VERSION matches expected format for branch $BRANCH"
   fi
@@ -265,7 +378,7 @@ if [ "$BRANCH" = "$MAIN" ]; then # this will be either an rc, resulting in a new
   PRERELEASE="$(echo "$MATCHES" | awk '{ print $4 }')"
 
   case "$RELEASE_LEVEL" in
-  rc|$RC) # then it's time to create a new release branch
+  $DEFAULT_RC|$RC) # then it's time to create a new release branch
       NEW_RELEASE_BRANCH="$BRANCH_PREFIX$MAJOR.$MINOR$BRANCH_SUFFIX"
       git checkout -b $NEW_RELEASE_BRANCH
 
@@ -274,14 +387,14 @@ if [ "$BRANCH" = "$MAIN" ]; then # this will be either an rc, resulting in a new
       setVersions $NEW_RELEASE_BRANCH_VERSION
 
       applyChanges "release $NEW_RELEASE_BRANCH_VERSION" $NEW_RELEASE_BRANCH_VERSION $ORIGIN $NEW_RELEASE_BRANCH
-      echo "INFO: created release branch $NEW_RELEASE_BRANCH and tagged $NEW_RELEASE_BRANCH_VERSION for release"
+      verbose "INFO: created release branch $NEW_RELEASE_BRANCH and tagged $NEW_RELEASE_BRANCH_VERSION for release"
 
       # return to master branch
       git checkout $MAIN
-      echo "INFO: checked out $MAIN"
+      verbose "INFO: checked out $MAIN"
 
       git cherry-pick $NEW_RELEASE_BRANCH # cherry pick from release branch to get release candidate commit in master
-      echo "INFO: cherry-picked $NEW_RELEASE_BRANCH $RC commit into $MAIN"
+      verbose "INFO: cherry-picked $NEW_RELEASE_BRANCH $RC commit into $MAIN"
 
       # advance master version
       NEXT_VERSION="$MAJOR.$(($MINOR+1)).0-$PRE.0"
@@ -292,7 +405,7 @@ if [ "$BRANCH" = "$MAIN" ]; then # this will be either an rc, resulting in a new
 
       # return to release branch & prepare for next prerelease
       git checkout $NEW_RELEASE_BRANCH
-      echo "INFO: checked out $NEW_RELEASE_BRANCH"
+      verbose "INFO: checked out $NEW_RELEASE_BRANCH"
 
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.0-$RC.1"
 
@@ -303,7 +416,7 @@ if [ "$BRANCH" = "$MAIN" ]; then # this will be either an rc, resulting in a new
       exit 0
       ;;
 
-  pre|$PRE)
+  $DEFAULT_PRE|$PRE)
       setVersions $VERSION
 
       applyChanges "release $VERSION" $VERSION
@@ -325,9 +438,9 @@ MATCHES="$($MATCH "^([0-9]{1,})\.([0-9]{1,})\.([0-9]{1,})\-$RC\.([0-9]{1,})$" "$
 set -e
 if [ -z "$MATCHES" ]; then
   echo "ERROR: the version does not match the format of major.minor.patch-$RC.n required in the release branch." >&2
-  exit 8
+  exit 3
 else
-  echo "INFO: version $VERSION matches expected format for branch $BRANCH"
+  verbose "INFO: version $VERSION matches expected format for branch $BRANCH"
 fi
 
 MAJOR="$(echo "$MATCHES" | awk '{ print $2 }')"
@@ -343,24 +456,24 @@ case "$RELEASE_LEVEL" in
 
     if [ $RELEASE_LEVEL = major ] && [ $MINOR != 0 ]; then
       echo "ERROR: this branch is not prepared for a major release because the minor version is $MINOR, not 0." >&2
-      exit 10
+      exit 3
     else
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-$RC.0"
     fi
     if [ $RELEASE_LEVEL = minor ] && [ $PATCH != 0 ]; then
       echo "ERROR: a minor release has already been performed in this release branch; only patch releases are allowed here now." >&2
-      exit 11
+      exit 3
     else
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-$RC.0"
     fi
     if [ $RELEASE_LEVEL = patch ] && [ $PATCH = 0 ]; then
       echo "ERROR: you must release a minor release before releasing a patch in this release branch." >&2
-      exit 12
+      exit 3
     else
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.$((PATCH+1))-$RC.0"
     fi
 
-    echo "INFO: $RELEASE_LEVEL ok in branch $BRANCH"
+    verbose "INFO: $RELEASE_LEVEL ok in branch $BRANCH"
 
     RELEASE_VERSION="$MAJOR.$MINOR.$PATCH"
 
@@ -375,7 +488,7 @@ case "$RELEASE_LEVEL" in
     exit 0
     ;;
 
-  rc|$RC)
+  $DEFAULT_RC|$RC)
     setVersions $VERSION
 
     applyChanges "release $VERSION" $VERSION
